/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReplyRouteImport } from './routes/reply'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as InteractRouteImport } from './routes/interact'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as IndexRouteImport } from './routes/index'

const ReplyRoute = ReplyRouteImport.update({
  id: '/reply',
  path: '/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractRoute = InteractRouteImport.update({
  id: '/interact',
  path: '/interact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/interact': typeof InteractRoute
  '/outreach': typeof OutreachRoute
  '/reply': typeof ReplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/interact': typeof InteractRoute
  '/outreach': typeof OutreachRoute
  '/reply': typeof ReplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/interact': typeof InteractRoute
  '/outreach': typeof OutreachRoute
  '/reply': typeof ReplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/configure' | '/interact' | '/outreach' | '/reply'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configure' | '/interact' | '/outreach' | '/reply'
  id: '__root__' | '/' | '/configure' | '/interact' | '/outreach' | '/reply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigureRoute: typeof ConfigureRoute
  InteractRoute: typeof InteractRoute
  OutreachRoute: typeof OutreachRoute
  ReplyRoute: typeof ReplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reply': {
      id: '/reply'
      path: '/reply'
      fullPath: '/reply'
      preLoaderRoute: typeof ReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interact': {
      id: '/interact'
      path: '/interact'
      fullPath: '/interact'
      preLoaderRoute: typeof InteractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigureRoute: ConfigureRoute,
  InteractRoute: InteractRoute,
  OutreachRoute: OutreachRoute,
  ReplyRoute: ReplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
