/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as InteractRouteImport } from './routes/interact'
import { Route as IndexRouteImport } from './routes/index'

const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractRoute = InteractRouteImport.update({
  id: '/interact',
  path: '/interact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interact': typeof InteractRoute
  '/outreach': typeof OutreachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interact': typeof InteractRoute
  '/outreach': typeof OutreachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interact': typeof InteractRoute
  '/outreach': typeof OutreachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/interact' | '/outreach'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/interact' | '/outreach'
  id: '__root__' | '/' | '/interact' | '/outreach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InteractRoute: typeof InteractRoute
  OutreachRoute: typeof OutreachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interact': {
      id: '/interact'
      path: '/interact'
      fullPath: '/interact'
      preLoaderRoute: typeof InteractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InteractRoute: InteractRoute,
  OutreachRoute: OutreachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
